Calculate height of section levels
bldrs-ai/ifctool pull request #31
Opened 2022-08-05 04:54 UTC by mkeshavarzi

Please note main.test.js and flags.test.js have been temp removed to allow push. Need to resolve.

2022-08-05 08:56 UTC, pablo-mayrgundter commented
Heya, I'm happy to review.  While you still have tests excluded please leave in draft.  I just flipped it.

Are there sample screens?

2022-08-05 11:12 UTC, mkeshavarzi commented
> Heya, I'm happy to review. While you still have tests excluded please leave in draft. I just flipped it.
> Are there sample screens?

Thanks! No graphics in this one yet, just calculating coordinates.

2022-08-05 13:49 UTC, pablo-mayrgundter commented
Got it checked out with ```git checkout upstream/CalculateSectionAndCamera```, though leaves the local client in "detached" state.  Anyways..

I uncomment calSecLevels and run:
```
> node lib/src/calLevSec.js ~/bldrs/3d\ models/IFC/Schependomlaan.ifc out.ifc
Input file:  /Users/pablo/bldrs/3d models/IFC/Schependomlaan.ifc
web-ifc: 0.0.34 threading: 0
```

But no output to out.ifc.

2022-08-05 18:50 UTC, mkeshavarzi commented
> Got it checked out with `git checkout upstream/CalculateSectionAndCamera`, though leaves the local client in "detached" state. Anyways..
> 
> I uncomment calSecLevels and run:
> 
> ```
> > node lib/src/calLevSec.js ~/bldrs/3d\ models/IFC/Schependomlaan.ifc out.ifc
> Input file:  /Users/pablo/bldrs/3d models/IFC/Schependomlaan.ifc
> web-ifc: 0.0.34 threading: 0
> ```
> 
> But no output to out.ifc.

The script doesn't output an ifc. It outputs a simple array of height values. 

To see the values, please uncomment line 31:
```console.log(elevValuesAll)```

and run:
```node lib/src/calLevSec.js ifcFileName```
(in your case):
```node lib/src/calLevSec.js ~/bldrs/3d\ models/IFC/Schependomlaan.ifc```

for example:
```mohammad@CheetahM1 tools % node lib/src/calLevSec.js lib/src/testdata/haus.ifc                
Input file:  lib/src/testdata/haus.ifc
web-ifc: 0.0.34 threading: 0
[ 0, 2.7 ]```

2022-08-10 17:52 UTC, pablo-mayrgundter commented
Hi Mohammed.  Sorry, I lost track.  Everything's running locally for me, though you have the existing tests deleted.  Just remove them from this PR.

What were you blocked on for testing?

2022-08-10 18:43 UTC, mkeshavarzi commented
> Hi Mohammed. Sorry, I lost track. Everything's running locally for me, though you have the existing tests deleted. Just remove them from this PR.
> 
> What were you blocked on for testing?

My block is I can't run main.test.js and flags.test.js, and hence cannot push the code without removing them.

2022-08-11 17:41 UTC, pablo-mayrgundter commented
Ah, I see.  Not sure how to fix this.  The version of ifclib that's being referenced is somehow being confused.  The main branch is ahead of your branch and has fixed those reference problems.

I tried updating tool/package.json to depend on the upstream version, 5.3.3, and then doing yarn install, but that doesn't seem to fix it:

```
> grep 5.3 tool/package.json
  "version": "5.3.1",
    "@bldrs-ai/ifclib": "^5.3.3"
```
```
> yarn install
> npm ls
@bldrs-ai/ifctool-root@5.3.1 /Users/pablo/c/pm/ifctool
├── @babel/core@7.18.6
├── @babel/eslint-parser@7.18.2
├── @babel/plugin-syntax-import-assertions@7.18.6
├── @babel/preset-env@7.18.6
├─┬ @bldrs-ai/ifclib@5.3.1 -> ./lib
│ ├── @log4js-node/log4js-api@1.0.2
│ ├── json2csv@5.0.7
│ └── web-ifc@0.0.35
├─┬ @bldrs-ai/ifctool@5.3.1 -> ./tool
│ ├── @bldrs-ai/ifclib@5.3.3.                    # GOOD!
│ └── log4js@6.6.0
├── esbuild@0.14.48
├── eslint-config-google@0.14.0
├── eslint-plugin-import@2.26.0
├── eslint@8.19.0
├── husky@7.0.4
├── jest@27.5.1
├── shx@0.3.4
└── three@0.142.0
```
However:
```
> grep version node_modules/\@bldrs-ai/ifclib/package.json
  "version": "5.3.1"
```
and indeed tests still fail with the bad ref to Exception which was indeed missing from from 5.3.1

2022-08-15 18:14 UTC, pablo-mayrgundter requested changes

2022-08-15 18:14 UTC, pablo-mayrgundter commented on tool/src/main.js
> +process.exitCode = await processArgs(process.argv.slice(2))
pls restore newline at eof

2022-08-15 18:14 UTC, pablo-mayrgundter commented on tool/src/main.test.js
> +})
newline at eof

2022-08-15 18:14 UTC, pablo-mayrgundter commented on tool/src/flags.js
> +      throw new Error
pls revert

2022-08-16 00:01 UTC, merged